"""临时脚本：提示用户保存图片"""
print("=" * 70)
print("请手动保存图片到当前目录")
print("=" * 70)
print("\n步骤：")
print("1. 右键点击上面的鼠标图片")
print("2. 选择'图片另存为'")
print("3. 保存为: E:\\stock_an\\mouse.png")
print("4. 或者将图片文件拖放到 E:\\stock_an 目录")
print("\n保存完成后，我们将运行测试脚本。")
print("=" * 70)