/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * 健康检查
     * @description 检查服务是否正常运行
     */
    get: {
      responses: {
        /** @description 服务正常运行 */
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
        /** @description 服务异常 */
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/stocks": {
    /**
     * 获取股票列表
     * @description 获取所有股票的基本信息列表
     */
    get: {
      parameters: {
        query?: {
          /** @description 返回记录数限制 */
          limit?: number;
          /** @description 偏移量 */
          offset?: number;
        };
      };
      responses: {
        /** @description 成功返回股票列表 */
        200: {
          content: {
            "application/json": components["schemas"]["StockListResponse"];
          };
        };
        /** @description 参数错误 */
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 服务器内部错误 */
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/stocks/{code}": {
    /**
     * 获取股票详情
     * @description 根据股票代码获取详细信息，包括基本信息、K线数据等
     */
    get: {
      parameters: {
        path: {
          /** @description 股票代码（如 000001.SZ） */
          code: string;
        };
      };
      responses: {
        /** @description 成功返回股票详情 */
        200: {
          content: {
            "application/json": components["schemas"]["StockDetailResponse"];
          };
        };
        /** @description 股票不存在 */
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 服务器内部错误 */
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/analysis/market-overview": {
    /**
     * 市场概览
     * @description 获取市场整体情况概览
     */
    get: {
      responses: {
        /** @description 成功返回市场概览数据 */
        200: {
          content: {
            "application/json": components["schemas"]["MarketOverviewResponse"];
          };
        };
        /** @description 服务器内部错误 */
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/analysis/signals": {
    /**
     * 获取买入信号
     * @description 获取最近生成的买入信号列表
     */
    get: {
      parameters: {
        query?: {
          /** @description 查询天数 */
          days?: number;
          /** @description 信号类型过滤 */
          signal_type?: "strong_buy" | "buy" | "watch" | "observe";
          /** @description 股票代码过滤 */
          stock_code?: string;
        };
      };
      responses: {
        /** @description 成功返回信号列表 */
        200: {
          content: {
            "application/json": components["schemas"]["SignalsResponse"];
          };
        };
        /** @description 参数错误 */
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 服务器内部错误 */
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/analysis/volume": {
    /**
     * 成交量分析
     * @description 获取成交量异动分析数据
     */
    get: {
      parameters: {
        query?: {
          /** @description 查询天数 */
          days?: number;
          /** @description 股票代码过滤 */
          stock_code?: string;
          /** @description 板块过滤 */
          board?: "main" | "gem" | "star" | "bse";
        };
      };
      responses: {
        /** @description 成功返回成交量分析数据 */
        200: {
          content: {
            "application/json": components["schemas"]["VolumeAnalysisResponse"];
          };
        };
        /** @description 参数错误 */
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description 服务器内部错误 */
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    BaseResponse: {
      /**
       * @description 请求是否成功
       * @example true
       */
      success: boolean;
      /**
       * @description 响应消息
       * @example 操作成功
       */
      message: string;
      /**
       * Format: date-time
       * @description 响应时间戳
       * @example 2024-01-01T12:00:00Z
       */
      timestamp?: string;
    };
    ErrorResponse: components["schemas"]["BaseResponse"] & {
      error: {
        /**
         * @description 错误代码
         * @example VALIDATION_ERROR
         */
        code?: string;
        /**
         * @description 错误详情
         * @example {
         *   "field": "days",
         *   "message": "参数必须为1-365之间的整数"
         * }
         */
        details?: Record<string, never>;
      };
    };
    HealthResponse: {
      /**
       * @example healthy
       * @enum {string}
       */
      status?: "healthy" | "unhealthy";
      /**
       * Format: date-time
       * @example 2024-01-01T12:00:00Z
       */
      timestamp?: string;
      /** @example stock-picker-backend */
      service?: string;
    };
    StockItem: {
      /**
       * @description 股票代码
       * @example 000001.SZ
       */
      code: string;
      /**
       * @description 股票名称
       * @example 平安银行
       */
      name: string;
      /**
       * @description 交易所
       * @example SZ
       * @enum {string}
       */
      exchange: "SZ" | "SH";
      /**
       * @description 行业
       * @example 银行
       */
      industry?: string;
      /**
       * Format: date-time
       * @description 创建时间
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description 更新时间
       */
      updated_at?: string;
    };
    KlineItem: {
      /**
       * Format: date
       * @description 交易日
       * @example 2024-01-01
       */
      date: string;
      /**
       * Format: float
       * @description 开盘价
       * @example 10.5
       */
      open: number;
      /**
       * Format: float
       * @description 最高价
       * @example 11.2
       */
      high: number;
      /**
       * Format: float
       * @description 最低价
       * @example 10.3
       */
      low: number;
      /**
       * Format: float
       * @description 收盘价
       * @example 10.8
       */
      close: number;
      /**
       * @description 成交量（股）
       * @example 1000000
       */
      volume: number;
      /**
       * Format: float
       * @description 成交额（元）
       * @example 10800000
       */
      amount?: number;
    };
    StockListResponse: components["schemas"]["BaseResponse"] & {
      data: components["schemas"]["StockItem"][];
      /**
       * @description 总记录数
       * @example 100
       */
      total?: number;
      /**
       * @description 返回记录数限制
       * @example 100
       */
      limit?: number;
      /**
       * @description 偏移量
       * @example 0
       */
      offset?: number;
    };
    StockDetailResponse: components["schemas"]["BaseResponse"] & {
      data: {
        stock?: components["schemas"]["StockItem"];
        klines?: components["schemas"]["KlineItem"][];
        volume_analysis?: components["schemas"]["VolumeAnalysisItem"];
        latest_signal?: components["schemas"]["SignalItem"];
      };
    };
    MarketOverviewResponse: components["schemas"]["BaseResponse"] & {
      data: {
        /**
         * @description 总股票数
         * @example 5000
         */
        totalStocks?: number;
        /**
         * @description 上涨股票数
         * @example 2500
         */
        upCount?: number;
        /**
         * @description 下跌股票数
         * @example 2000
         */
        downCount?: number;
        /**
         * @description 平盘股票数
         * @example 500
         */
        flatCount?: number;
        /**
         * @description 今日信号数
         * @example 50
         */
        todaySignals?: number;
        /**
         * @description 成交量异动数
         * @example 30
         */
        volumeSurges?: number;
        topVolumeSurge?: components["schemas"]["VolumeSurgeItem"][];
      };
    };
    VolumeAnalysisItem: {
      /** @description 股票代码 */
      stock_code?: string;
      /**
       * Format: date
       * @description 分析日期
       */
      date?: string;
      /**
       * Format: float
       * @description 量比
       * @example 2.5
       */
      volume_ratio?: number;
      /** @description 20日平均成交量 */
      avg_volume_20?: number;
      /** @description 是否成交量异动 */
      is_volume_surge?: boolean;
      /** @description 分析结果 */
      analysis_result?: string;
    };
    VolumeSurgeItem: {
      /** @description 股票代码 */
      stock_code?: string;
      /** @description 股票名称 */
      name?: string;
      /**
       * Format: float
       * @description 量比
       */
      volume_ratio?: number;
      /**
       * Format: date
       * @description 日期
       */
      date?: string;
    };
    VolumeAnalysisResponse: components["schemas"]["BaseResponse"] & {
      data: {
        volumeAnalysis?: components["schemas"]["VolumeAnalysisItem"][];
        volumeSurges?: components["schemas"]["VolumeSurgeItem"][];
        /** @description 总记录数 */
        total?: number;
      };
    };
    SignalItem: {
      /** @description 股票代码 */
      stock_code: string;
      /** @description 股票名称 */
      stock_name?: string;
      /**
       * @description 信号类型
       * @enum {string}
       */
      signal_type: "strong_buy" | "buy" | "watch" | "observe";
      /**
       * Format: float
       * @description 置信度
       * @example 0.85
       */
      confidence: number;
      /**
       * Format: float
       * @description 价格
       */
      price?: number;
      /** @description 成交量 */
      volume?: number;
      /**
       * Format: date-time
       * @description 创建时间
       */
      created_at?: string;
    };
    SignalsResponse: components["schemas"]["BaseResponse"] & {
      data: {
        signals?: components["schemas"]["SignalItem"][];
        summary?: {
          [key: string]: {
            count?: number;
            /** Format: float */
            avgConfidence?: number;
          };
        };
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
